service: lambda-apigw-sockets
frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  websocketsApiRouteSelectionExpression: $request.body.action
  layers:
    - ${ssm:/aws/service/powertools/python/x86_64/python3.12/latest}
  environment:
    CONNECTIONS_TABLE:
      Ref: ConnectionsTable
    POWERTOOLS_SERVICE_NAME: ${self:service}
  logRetentionInDays: 7

package:
  patterns:
    - "!**"
    - "functions/**"
    - "utils/**"
    - "!functions/index.yml"
    - "!**/__pycache__/**"

functions:
  - ${file(functions/index.yml)}

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/cognito.yml)}
  - Outputs:
      WebSocketEndpoint:
        Value:
          Fn::Join:
            - ""
            - - "wss://"
              - Ref: WebsocketsApi
              - ".execute-api."
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
              - "/"
              - ${sls:stage}
